# PyTorch

- Soporte de GPU: Ofrece soporte completo para la aceleración por GPU.
- Computación de tensores: PyTorch permite realizar operaciones sobre tensores, en muchas ocasiones de manera similizar a como se trabaja con Numpy.
- Autograd para la diferenciación automática: El módlulo `autograd` es una característica central de PyTorch, facilitando la diferenciación automática para el entrenamiento de redes neuronales.
- Ecosistema amplio: Existen librerías que trabajan sobre PyTorch como PyTorch Lightnining o HuggingFace Transformers.
- Implementación de modelos del estado del arte: PyTorch se utiliza para el entrenamiento y desarrollo de modelos del estado del arte.
- Felixibilidad para la investigación: Es ampliamente utilizado en el ámbito de la investigación para experimentar con arquitecturas de modelos complejas.

In [1]:
import torch

## Configuración inicial

In [2]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device seleccionado: {device}")

Device seleccionado: cpu


## Creación de tensores

In [3]:
# TODO: Crear un tensor de ceros
zeros = torch.zeros((3, 3))
print(f"Tensor de ceros:\n{zeros}")

Tensor de ceros:
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [4]:
# TODO: Crear un tensor de unos
ones = torch.ones((2, 2))
print(f"Tensor de unos:\n{ones}")

Tensor de unos:
tensor([[1., 1.],
        [1., 1.]])


In [5]:
# TODO: Crear un tensor con valores aleatorios
random_tensor = torch.rand((3, 3))
print(f"Tensor con valores aleatorios:\n{random_tensor}")

Tensor con valores aleatorios:
tensor([[0.9183, 0.8927, 0.6468],
        [0.6137, 0.7950, 0.5781],
        [0.2972, 0.7251, 0.3358]])


In [6]:
# TODO: Crear un tensor de una secuencia
seq_tensor = torch.arange(0, 10)
print(f"Tensor de una secuencia:\n{seq_tensor}")

Tensor de una secuencia:
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [7]:
# TODO: Crear un tensor con un tipo de dato específico (int32)
dtype_tensor = torch.zeros((2, 2), dtype=torch.int32)
print(f"Tensor con tipo de dato int32:\n{dtype_tensor}")

Tensor con tipo de dato int32:
tensor([[0, 0],
        [0, 0]], dtype=torch.int32)


In [8]:
import numpy as np

# TODO: Crear tensor desde numpy
numpy_array = np.array([1, 2, 3, 4, 5])
torch_tensor = torch.from_numpy(numpy_array)
print(f"Tensor de PyTorch creado desde el array de NumPy:\n{torch_tensor}")

Tensor de PyTorch creado desde el array de NumPy:
tensor([1, 2, 3, 4, 5])


## Operaciones con Tensores

In [9]:
a = torch.tensor([2, 3, 4], dtype=torch.float32)
b = torch.tensor([4, 5, 6], dtype=torch.float32)

print(f"Tensor a: {a}")
print(f"Tensor b: {b}")

Tensor a: tensor([2., 3., 4.])
Tensor b: tensor([4., 5., 6.])


In [10]:
# TODO: Suma
suma = torch.add(a, b)
print(f"Suma de tensores:\n{suma}")

Suma de tensores:
tensor([ 6.,  8., 10.])


In [11]:
# TODO: Resta
resta = a - b
print(f"Resta de tensores:\n{resta}")

Resta de tensores:
tensor([-2., -2., -2.])


In [12]:
# TODO: División elemento a elemento
div = a / b
print(f"\nDivisión elemento a elemento:\n{div}")


División elemento a elemento:
tensor([0.5000, 0.6000, 0.6667])


In [13]:
# TODO: Multiplicación de matrices (producto punto)
c = torch.tensor([[1, 2], [3, 4]])
d = torch.tensor([[5, 6], [7, 8]])

print(f"Tensor c:\n{c}")
print(f"\nTensor d:\n{d}")

mult = torch.mm(c, d)

print(f"\nProducto punto:\n{mult}")

Tensor c:
tensor([[1, 2],
        [3, 4]])

Tensor d:
tensor([[5, 6],
        [7, 8]])

Producto punto:
tensor([[19, 22],
        [43, 50]])


In [14]:
# TODO: Multiplicación de matrices elemento a elemento
mult_elem_by_elem = c * d
print(f"Producto punto:\n{mult_elem_by_elem}")

Producto punto:
tensor([[ 5, 12],
        [21, 32]])


In [15]:
# TODO: Exponenciación elemento a elemento
exp_elem_by_elem = a ** 2
print(f"Exponenciación elemento a elemento:\n{exp_elem_by_elem}")

Exponenciación elemento a elemento:
tensor([ 4.,  9., 16.])


## Indexación, concatenación y forma (shape)

In [16]:
tensor = torch.arange(1, 10).reshape(3, 3)
print(f"Tensor para indexar:\n{tensor}")

Tensor para indexar:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [17]:
# TODO: Obtener la fila 1
fila = tensor[1]
print(f"Primer fila del tensor:\n{fila}")

Primer fila del tensor:
tensor([4, 5, 6])


In [18]:
# TODO: Obtener el elemento de la posición 1, 1
elemento = tensor[1, 1]
print(f"Elemento en la posición (1,1):\n{elemento}")

Elemento en la posición (1,1):
5


In [19]:
# TODO: Obtener la columna 1
columna = tensor[:, 1]
print(f"Elemento en la posición (1,1):\n{columna}")

Elemento en la posición (1,1):
tensor([2, 5, 8])


In [20]:
# TODO: Cambio de tamaño y forma a una fila y 9 columnas
reshape_tensor = tensor.view(1, 9)
print(f"Tensor reconfigurado:\n{reshape_tensor}")

Tensor reconfigurado:
tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])


## Módulo autograd

- Diferenciación automática: Proporciona una forma automática de calcular los gradientes de los tensores con respecto a las variables que afectan a su cálculo.
- Facilidad para el cálculo del backpropagation: Calcula la operación de backpropagation de manera eficiente, calculando los gradientes que se necesitan para actualizar los parámetros del modelo en el proceso de aprendizaje.
- Optimización de parámetros: Los gradientes calculados por `autograd` son utilizados por algoritmos de optimización, como el descenso de gradiente, para ajustar los parámetros del modelo en el proceso de aprendizaje.

In [21]:
# TODO Crear un tensor y establecer requires_grad=True para calcular automáticamente gradientes
x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)
print(f"Tensor original: {x}")

Tensor original: tensor([1., 2., 3.], requires_grad=True)


In [22]:
# TODO: x = x * 2
# TODO: z = y * y * 2
# TODO: out igual a la media de z
y = x * 2
z = y * y * 3
out = z.mean()
print(f"Resultado de y: {y}")
print(f"\nResultado de x: {x}")
print(f"\nResultado de la operación: {out}")

Resultado de y: tensor([2., 4., 6.], grad_fn=<MulBackward0>)

Resultado de x: tensor([1., 2., 3.], requires_grad=True)

Resultado de la operación: 56.0


In [23]:
# TODO: Calcular los gradientes. TIP: Mirar función backward
out.backward()

# TODO: Mostras el gradiente de x
x_grad = x.grad
print(f"Gradientes: {x_grad}")

Gradientes: tensor([ 8., 16., 24.])


## Implementación del algoritmo de backpropagation

In [24]:
x = torch.tensor([[1.], [2.], [3.], [4.]], requires_grad=False)
y = torch.tensor([[3.], [5.], [7.], [9.]], requires_grad=False)

print(f"Datos de entrada:\n{x}")
print(f"\nDatos de salida:\n{y}")

Datos de entrada:
tensor([[1.],
        [2.],
        [3.],
        [4.]])

Datos de salida:
tensor([[3.],
        [5.],
        [7.],
        [9.]])


In [25]:
# TODO: Crear un tensor w de 1 elemento aleatorio y con requires_grad=True
# TODO: Crear un tensor b de 1 elemento aleatorio y con requires_grad=True
w = torch.randn(1, requires_grad=True)
b = torch.randn(1, requires_grad=True)

print(f"Pesos:\n{w}")
print(f"\nSesgos (bias):\n{b}")

Pesos:
tensor([-0.6476], requires_grad=True)

Sesgos (bias):
tensor([0.0490], requires_grad=True)


In [26]:
# TODO: Simular el entrenamiento de una red neuronal
learning_rate = 0.01
num_epochs = 1000

for epoch in range(num_epochs):
    # TODO: Forward pass: calcular la predicción
    y_pred = w * x + b

    # TODO: Calcular la pérdida (Mean Squared Error)
    loss = ((y_pred - y) ** 2).mean()

    # TODO: Backpropagation: calcular los gradientes
    loss.backward()

    # TODO: Actualizar los parámetros (w, b) usando descenso del gradiente
    with torch.no_grad():
        w -= learning_rate * w.grad
        b -= learning_rate * b.grad

    # TODO: Poner a cero los gradientes después de la actualización. TIP: función zero_
    w.grad.zero_()
    b.grad.zero_()

    # Imprimir la pérdida cada 100 épocas
    if epoch % 100 == 0:
        print(f"Epoch {epoch + 1}:\tw = {w.item()},\tb = {b.item()},\tloss = {loss.item()}")

Epoch 1:	w = -0.20292255282402039,	b = 0.20035314559936523,	loss = 66.06864929199219
Epoch 101:	w = 2.011380910873413,	b = 0.9665387868881226,	loss = 0.00018812043708749115
Epoch 201:	w = 2.008432626724243,	b = 0.9752069711685181,	loss = 0.00010328129428671673
Epoch 301:	w = 2.0062479972839355,	b = 0.9816300868988037,	loss = 5.669757956638932e-05
Epoch 401:	w = 2.004629611968994,	b = 0.9863888025283813,	loss = 3.112785634584725e-05
Epoch 501:	w = 2.0034303665161133,	b = 0.9899147152900696,	loss = 1.7089725588448346e-05
Epoch 601:	w = 2.002542018890381,	b = 0.9925269484519958,	loss = 9.38251287152525e-06
Epoch 701:	w = 2.0018835067749023,	b = 0.9944623708724976,	loss = 5.152253834239673e-06
Epoch 801:	w = 2.0013957023620605,	b = 0.9958962202072144,	loss = 2.82952532870695e-06
Epoch 901:	w = 2.00103497505188,	b = 0.9969584345817566,	loss = 1.554585878693615e-06
